// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9hDMH1ocNwBIaq6sklcU74xDfLVMbURE',
    appId: '1:934229348374:web:cae7ff1f3a4234e090e537',
    messagingSenderId: '934229348374',
    projectId: 'imagevaul',
    authDomain: 'imagevaul.firebaseapp.com',
    storageBucket: 'imagevaul.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0pMNGyaHDqaC2mQZu3hzm6IwmWTMF2o',
    appId: '1:934229348374:android:52e5629e03f74e0590e537',
    messagingSenderId: '934229348374',
    projectId: 'imagevaul',
    storageBucket: 'imagevaul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjdxOwMXOo6P8rVmLN1JdXo8FJDddFeI',
    appId: '1:934229348374:ios:ebb718d2427eb95690e537',
    messagingSenderId: '934229348374',
    projectId: 'imagevaul',
    storageBucket: 'imagevaul.appspot.com',
    iosBundleId: 'com.example.securedImageVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjdxOwMXOo6P8rVmLN1JdXo8FJDddFeI',
    appId: '1:934229348374:ios:5ae53e73b3d6c93890e537',
    messagingSenderId: '934229348374',
    projectId: 'imagevaul',
    storageBucket: 'imagevaul.appspot.com',
    iosBundleId: 'com.example.securedImageVault.RunnerTests',
  );
}
